### PR TITLE
Add `grid_proxy` to database

### LINKED ISSUE #207: Add grid proxy to database
We assume that for testing SLURM on plgrid now it should be enough to add or update manually `grid_proxy` to the database.
The flow:
1. We login to ares, generate grid_proxy string
2. We login to C3 machine, run some script to add/update `grid_proxy` in the DB
3. We login to UI (running on C3) and submit SLURM jobs as authenticated user

### PR DESCRIPTION
**Pull request by p1003**

### CODE REVIEW

**Comment by p1003** [comment]
`call_api_example.py` currently works and can be tested

**Comment by grzanka** [comment]
@p1003 can you add an entry to the readme how to add the `grid_proxy` to the user DB entry after initial deploy of the backend on C3 ? I would like to do it easily from command line ?

**Comment by p1003** [comment]
> @p1003 can you add an entry to the readme how to add the `grid_proxy` to the user DB entry after initial deploy of the backend on C3 ? I would like to do it easily from command line ?

Forgot about manual adding `grid_proxy`. I'll work on it tomorrow

**Review by p1003 — COMMENTED** [review]
@grzanka approve when you check this PR

**Review by grzanka — APPROVED** [review]
LGTM

**Pull request merged**
