### PR TITLE
Support for modulator wheels, converter update

### PR DESCRIPTION
**Pull request by grzanka**
Still missing:
- [x] update testing JSON files (`yaptide/tests/res`)
- [x] fix docker files : nginx and cors
- [x] write down new issues: 
   - [ ] separate repo for examples (and expected output files) https://github.com/yaptide/ui/issues/1085
   - [ ] improved tests on converter covering modulator and lack of modulator https://github.com/yaptide/converter/issues/136

To be tested with:
- https://github.com/yaptide/deploy/pull/32
- https://github.com/yaptide/ui/pull/1042
- https://github.com/yaptide/converter/pull/137

### CODE REVIEW

**Comment by grzanka** [comment]
Better to split dockerfiles for nginx and flask into separate ones, see:
https://testdriven.io/blog/dockerizing-flask-with-postgres-gunicorn-and-nginx/

**Review by p1003 — DISMISSED** [review]
LGBT

**Review by Derstilon — APPROVED** [review]

**Pull request merged**
